# This is a basic workflow to help you get started with Actions

name: FindReplace

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: #[ master ]
      - "[fF][nN][rR]-*" 
    #paths:
    #- '**.md'
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  FindReplace:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: "0"
    
    - name: '' #get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
    
    - name: '' #get changed files
      id: getDirName
      run: |
        echo "::set-output name=dirs::$(dirname ${{ steps.getfile.outputs.files }})"
    
    #- name: echo output
      #run: |
        #echo ${{ steps.getfile.outputs.files }}
        #echo ${{ steps.getDirName.outputs.dirs }}
        
    - name: Find and Replace
      #id: hellodemo
      uses: shitiomatic/str-replace@master
      with:
        find: "aggregate"
        replace: "team"
        include: ${{ steps.getfile.outputs.files }} #${{ steps.getDirName.outputs.dirs }} #"test/"
   
    #- name: Test
    # run: echo ${{ steps.hellodemo.outputs.modifiedFiles }}
          
    - name: Check outputs and modified files
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Find and Replace Commit"
        git push 
             
           
        
            
          
          
